language: c
dist: xenial
git:
  quite: true
  depth: 3

env:
  global:
  - CTEST_OUTPUT_ON_FAILURE=TRUE
  - CTEST_PARALLEL_LEVEL=2

before_script:
- cd tests
- mkdir build
- cd build

matrix:
  fast_finish: true
  include:

  - name: "Clang 4.0"
    addons:
      apt:
        packages:
        - clang-4.0
    script:
    - cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_C_COMPILER="clang-4.0" ..
    - make
    - make test

  - name: "Codecov"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-8
    script:
    - cmake -DCMAKE_BUILD_TYPE=COVERAGE -DCMAKE_C_COMPILER="gcc-8" ..
    - make
    - make test
    after_success:
    - bash <(curl -s https://codecov.io/bash) -R "$TRAVIS_BUILD_DIR" -x gcov-8

  - name: "Address Sanitizer"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-8
    script:
    - cmake -DCMAKE_BUILD_TYPE=ASAN -DCMAKE_C_COMPILER="gcc-8" ..
    - make
    - make test

  - name: "Build Nano S"
    services:
    - docker
    before_script:
    script:
    - |
      docker run \
      -v $(pwd):/root/project \
      -e BOLOS_ENV=/opt/bolos \
      -e BOLOS_SDK=/root/project/dev/sdk/nanos-secure-sdk \
      zondax/ledger-docker-bolos \
      make -C /root/project

  - name: "Build Blue"
    services:
    - docker
    before_script:
    script:
    - |
      docker run \
      -v $(pwd):/root/project \
      -e BOLOS_ENV=/opt/bolos \
      -e BOLOS_SDK=/root/project/dev/sdk/blue-secure-sdk \
      zondax/ledger-docker-bolos \
      make -C /root/project
