#ifndef TEST_CONSTANTS_H
#define TEST_CONSTANTS_H

#ifndef TEST_FOLDER
#define TEST_FOLDER "kerl-spec/test_vectors"
#endif

#define MAX_NUM_HASHES 5
#define NUM_HASH_TRITS 243
#define NUM_HASH_TRYTES 81
#define NUM_HASH_TRINTS 49
#define NUM_HASH_BYTES 48

#define NUM_TRINTS(X) (((X) / NUM_HASH_TRITS) * NUM_HASH_TRINTS)
#define NUM_BYTES(X) (((X) / NUM_HASH_TRITS) * NUM_HASH_BYTES)

#define MAX_NUM_TRITS (NUM_HASH_TRITS * MAX_NUM_HASHES)
#define MAX_NUM_TRINTS NUM_TRINTS(MAX_NUM_TRITS)
#define MAX_NUM_BYTES NUM_BYTES(MAX_NUM_TRITS)
#define TRITS_PER_TRYTE 3
#define MAX_NUM_TRYTES (MAX_NUM_TRITS / TRITS_PER_TRYTE)

#endif // TEST_CONSTANTS_H
