name: Build

on: [push]

env:
  DOCKER_IMAGE: 'wollac/ledger-bolos'

jobs:  
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        sdk-version: ['nanos-secure-sdk', 'blue-secure-sdk']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Build using ${{ matrix.sdk-version }}
      run: docker run -u $(id -u):$(id -g) -v $(pwd):/project -e BOLOS_SDK=/project/dev/sdk/${{ matrix.sdk-version }} $DOCKER_IMAGE make -C /project
