name: Build

on: [push, pull_request]

jobs:  
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        device: ['nanos', 'nanox', 'nanosplus']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Build using ${{ matrix.device }}
      run: ./build.sh -m ${{ matrix.device }}
